server:
  port: 80


eureka:
  client: #客户端注册到eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://payment.mall.com:7001/eureka,http://cart.mall.com:7002/eureka/,http://order.mall.com:7003/eureka/
    register-with-eureka: false  #不能把自己注册到eureka服务器

feign:
  hystrix:
    enabled: true